name: On merge changeset

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    if: contains(github.event.pull_request.head.ref, 'changeset-release')

    name: 'Upload script'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: 'Setup Javascript'
        uses: ./.github/actions/setup-project

      - name: Bundle the script into a single file
        run: deno task build

      - name: Publish the script to Bunny
        uses: 'BunnyWay/actions/deploy-script@debug'
        with:
          script_id: 222
          base: "https://testfluffle.net/api"
          file: "dist/index.ts"
